services:
  nginx:
    image: 'nginx:1.27.3-bookworm'
    volumes:
      - './nginx/production.conf:/etc/nginx/nginx.conf'
      - './certs:/certs'
    command:
      - nginx
      - '-g'
      - daemon off;
    restart: always
    ports:
      - '443:443'
    networks:
      - public
    depends_on:
      app:
        condition: service_started
    healthcheck:
      test:
        - CMD
        - service
        - nginx
        - status
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
      start_interval: 1s
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    env_file:
      - .env.production
    volumes:
      - 'app_build:/app/.next'
    command:
      - yarn
      - start
    restart: always
    networks:
      - public
      - internal
    depends_on:
      app_build:
        condition: service_completed_successfully
  shop-app: null
  build:
    context: .
    dockerfile: Dockerfile
    target: production
  env_file:
    - .env.production
  volumes:
    - 'app_build:/app/.next'
  command:
    - yarn
    - start
  restart: always
  ports: '-3001:3000'
  networks:
    - public
    - internal
  depends_on:
    app_build:
      condition: service_completed_successfully
  app_build:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    env_file:
      - .env.production
    volumes:
      - 'app_build:/app/.next'
    command:
      - yarn
      - build
volumes:
  app_build: {}
networks:
  public: {}
  internal: {}
