import {
  AlertTriangle,
  ArrowUpLeft,
  BarChart3,
  CheckCircle2,
  ClipboardList,
  DatabaseZap,
  Home,
  LifeBuoy,
  PackageCheck,
  RefreshCw,
  RotateCcw,
  Settings,
  ShieldCheck,
  Store,
  TimerReset,
} from 'lucide-react';
import type {
  MetricCard,
  NavItem,
  PaidOrderRecoveryRow,
  TimelineItem,
} from './adminShopDashboardTypes';

export const adminShopNavItems: NavItem[] = [
  { label: 'Site Root', href: '/', icon: ArrowUpLeft },
  { label: 'Admin Dashboard', href: '/admin', icon: Home },
  { label: 'Shop Overview', href: '/admin/shop', icon: Home },
  { label: 'Paid Order Recovery', href: '/admin/shop/paid-order-recovery', icon: ClipboardList },
  { label: 'Checkout Recovery OTPs', icon: LifeBuoy },
  { label: 'Django OTP Intents', icon: ShieldCheck },
  { label: 'Merchize Fulfillment', icon: PackageCheck },
  { label: 'Failed Queue', icon: AlertTriangle, count: '12' },
  { label: 'Reconciliation', href: '/admin/shop/paypal-reconciliation', icon: RotateCcw },
  { label: 'Expired OTP Cleanup', icon: TimerReset },
  { label: 'Support Cases', icon: ClipboardList, count: '5' },
  {
    label: 'Catalog & Snapshots',
    href: '/admin/shop/merchize-catalog-snapshots',
    icon: Store,
  },
  { label: 'Reports', icon: BarChart3 },
  { label: 'Audit Logs', href: '/admin/admin-ops/audit-logs', icon: DatabaseZap },
  { label: 'Settings', href: '/admin/admin-ops', icon: Settings },
];

export const adminShopMetricCards: MetricCard[] = [
  {
    title: 'Paid Order Recovery',
    metric: '1,248',
    caption: 'This month',
    action: 'Review Orders',
    href: '/admin/shop/paid-order-recovery',
    icon: ClipboardList,
    state: 'healthy',
    tone: 'blue',
  },
  {
    title: 'Checkout Recovery OTPs',
    metric: '28',
    caption: 'Needs attention',
    action: 'Open Recoveries',
    icon: RefreshCw,
    state: 'action',
    tone: 'cyan',
  },
  {
    title: 'Django OTP Intents',
    metric: '16',
    caption: 'Pending verification',
    action: 'Open Intents',
    icon: ShieldCheck,
    state: 'pending',
    tone: 'cyan',
  },
  {
    title: 'Merchize Fulfillment',
    metric: '92',
    caption: 'In progress',
    action: 'View Fulfillment',
    icon: PackageCheck,
    state: 'healthy',
    tone: 'cyan',
  },
  {
    title: 'Failed Queue',
    metric: '12',
    caption: 'Requires action',
    action: 'Open Queue',
    icon: AlertTriangle,
    state: 'critical',
    tone: 'rose',
  },
  {
    title: 'Reconciliation',
    metric: '0',
    caption: 'Payment attention',
    action: 'Open PayPal Reconciliation',
    href: '/admin/shop/paypal-reconciliation',
    icon: BarChart3,
    state: 'review',
    tone: 'amber',
  },
  {
    title: 'Expired OTP Cleanup',
    metric: '87',
    caption: 'Eligible for cleanup',
    action: 'Run Cleanup',
    icon: TimerReset,
    state: 'ready',
    tone: 'violet',
  },
  {
    title: 'Support Cases',
    metric: '5',
    caption: 'Open cases',
    action: 'View Cases',
    icon: LifeBuoy,
    state: 'open',
    tone: 'blue',
  },
  {
    title: 'Catalog & Snapshots',
    metric: '2',
    caption: 'Sync issues',
    action: 'Open Tool',
    href: '/admin/shop/merchize-catalog-snapshots',
    icon: Store,
    state: 'warning',
    tone: 'emerald',
  },
];

export const adminPaidOrderRecoveryRows: PaidOrderRecoveryRow[] = [
  {
    orderToken: '45e493b8-c45b-4671-94dd-667dc8b0196b',
    status: 'failed',
    customer: 'customer@example.com',
    amount: '$149.99 USD',
    step: 'Fulfillment Retry',
    error: 'Merchize API Timeout',
    supportRef: 'SUP-8123',
    updated: '2m ago',
  },
  {
    orderToken: '31f91e89-a7f2-492c-8d88-66ef54094e22',
    status: 'recovery',
    customer: 'jane@example.com',
    amount: '$89.00 USD',
    step: 'Awaiting OTP',
    error: '-',
    supportRef: 'SUP-8122',
    updated: '6m ago',
  },
  {
    orderToken: '6a7b5d3e-6e02-4c69-8a40-c0326dd1f103',
    status: 'pending',
    customer: 'mike@example.com',
    amount: '$239.99 USD',
    step: 'Django OTP Sent',
    error: '-',
    supportRef: 'SUP-8121',
    updated: '11m ago',
  },
  {
    orderToken: 'f1b3bd59-38d2-40fb-a771-2184601453f4',
    status: 'completed',
    customer: 'alex@example.com',
    amount: '$59.99 USD',
    step: 'Completed',
    error: '-',
    supportRef: 'SUP-8120',
    updated: '18m ago',
  },
  {
    orderToken: 'bbdf77ca-705f-4d3e-bb6a-1cf82283f5cb',
    status: 'failed',
    customer: 'sarah@example.com',
    amount: '$299.00 USD',
    step: 'PayPal Capture',
    error: 'Capture Failed',
    supportRef: 'SUP-8119',
    updated: '25m ago',
  },
  {
    orderToken: '17514631-ae28-4681-b4c5-e6b14b08dfe7',
    status: 'pending',
    customer: 'bruce@example.com',
    amount: '$129.50 USD',
    step: 'Payment Authorized',
    error: '-',
    supportRef: 'SUP-8118',
    updated: '32m ago',
  },
  {
    orderToken: '1c5039ff-68f6-45a7-8b67-e1e6e6c37812',
    status: 'completed',
    customer: 'lisa@example.com',
    amount: '$42.00 USD',
    step: 'Fulfilled',
    error: '-',
    supportRef: 'SUP-8117',
    updated: '45m ago',
  },
  {
    orderToken: '964a28af-47fa-4201-a966-6d24341ba140',
    status: 'failed',
    customer: 'tony@example.com',
    amount: '$199.00 USD',
    step: 'Fulfillment Retry',
    error: 'Address Validation Failed',
    supportRef: 'SUP-8116',
    updated: '1h ago',
  },
];

export const adminTimelineItems: TimelineItem[] = [
  { label: 'Payment Authorized', time: 'Jun 15, 14:30:11', state: 'done' },
  { label: 'Payment Captured', time: 'Jun 15, 14:30:14', state: 'done' },
  { label: 'Django Intent Verified', time: 'Jun 15, 14:30:28', state: 'done' },
  { label: 'Fulfillment Initiated', time: 'Jun 15, 14:31:02', state: 'done' },
  { label: 'Fulfillment Failed', time: 'Jun 15, 14:32:05', state: 'failed' },
  { label: 'Retry Scheduled', time: 'Pending', state: 'pending' },
];

export const adminRecoveryActions = [
  { label: 'Retry Fulfillment', icon: RefreshCw, tone: 'cyan' as const },
  { label: 'View in Ledger', icon: DatabaseZap },
  { label: 'Regenerate Receipt', icon: ClipboardList },
  { label: 'Mark Resolved', icon: CheckCircle2 },
];
